// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repository

import (
	"database/sql"
)

type SchemaMigration struct {
	Version string
}

type SyncServer struct {
	ID      string
	Version int64
}

type WalOperation struct {
	ServerVersion int64
	Key           string
	TableName     string
	Operation     string
	Value         sql.NullString
	ValueKey      sql.NullString
	Version       int64
	ClientID      string
}
