(lang dune 3.23)

(name minibuild)

(generate_opam_files true)

(source
 (github username/reponame))

(authors "Author Name <author@example.com>")

(maintainers "Maintainer Name <maintainer@example.com>")

(license LICENSE)

(documentation https://url/to/documentation)

(package
 (name minibuild)
 (synopsis "A short synopsis")
 (description "A longer description")
 (depends
  ocaml
  ppx_expect
  cmdliner
  (hegel :with-test)
  (ppx_hegel_test :with-test))
 (tags
  ("add topics" "to describe" your project)))
